### PR TITLE
Identify Result types by the last segment in the path

### LINKED ISSUE #2: Result<T, E> detection doesn't work reliably
Currently, `Result` detection looks to see if the first term in the path `== "Result"`. This is brittle, as the code below demonstrates:

```rust
#[logfn(INFO, fmt = "fibonacci() -> {:?}", err = "Error", ok = "Info")]
fn fibonacci(n: u32) -> std::result::Result<u32, u32> {
    match n {
        0 => Ok(1),
        1 => Ok(1),
        3 => Err(3),
        _ => Ok(fibonacci(n - 1)? + fibonacci(n - 2)?),
    }
}
```

This means functions that return mod-specific `Result` types such as `io::Result` or `fmt::Result` won't have the correct log level.

Unfortunately, there's no good way to tell if a particular type is an alias of `Result`. This leaves three options for how to proceed:

1. Check if the _last_ ident term in the return type path is `Result`. This would catch most cases.
2. Assume that the return type is a result if `err` and/or `ok` are specified. Since these don't make sense to use otherwise, this is a lightweight way to solve the problem.
3. Add a new meta item to the attribute which opts into the `Result` behavior. This approach preserves compatibility with existing attribute usage, but at the expense of conciseness.

### PR DESCRIPTION
**Pull request by TedDriggs**
This works with types such as `io::Result<T>`

Fixes #2

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -148,25 +148,25 @@ fn get_literal_str(l: Lit) -> String {
...
-                    if tp.path.segments.is_empty() {
-                        false
-                    } else {
-                        tp.path.segments[0].ident == "Result"
-                    }
-                },
-                _ => false,
-            }
+    if let ReturnType::Type(_, t) = &f.decl.output {
+        if let Type::Path(path) = t.as_ref() {
```
Comment (elichai) [inline src/lib.rs]: Please keep this a match because in the future I might want to add support for other special cases(i.e tuple)

**Review by elichai — CHANGES_REQUESTED** [review]

File: src/lib.rs (hunk 1 above)
Comment (TedDriggs) [reply src/lib.rs]: Done
